### ISSUE TITLE
itens adicionados ao carrinho não são removidos do banco de dados depois

### ISSUE THREAD

**Issue by juliafelixcor** [mateusioliveira/cantinho_cesar#3]
Os itens adicionados ao carrinho não são removidos do banco de dados após o usuário sair de sua conta, todos os itens continuam lá mesmo que no carrinho só mostre o que o usuário colocou no momento.

![WhatsApp Image 2023-10-26 at 17 54 02](https://github.com/Matheus-Rian/cantinho_cesar/assets/98843736/ecf0ee57-a217-4b85-ac85-52a72a8b353c)

![WhatsApp Image 2023-10-26 at 17 54 34](https://github.com/Matheus-Rian/cantinho_cesar/assets/98843736/2d80dba5-a4f3-4f44-9f31-339933cd262c)

**Comment by Victorgalves** [comment]
corrigido
